#!/usr/bin/env bash

openwrt_vm_env_source="${BASH_SOURCE[0]:-}"

if [[ -z "${openwrt_vm_env_source}" && -n "${ZSH_VERSION:-}" ]]; then
  openwrt_vm_env_source="$(eval 'printf %s "${(%):-%N}"')"
fi

if [[ -z "${openwrt_vm_env_source}" ]]; then
  openwrt_vm_env_source="scripts/openwrt-vm/env.sh"
fi

case "${openwrt_vm_env_source}" in
  /*) ;;
  *) openwrt_vm_env_source="${PWD}/${openwrt_vm_env_source}" ;;
esac

OPENWRT_VM_SCRIPT_DIR="$(cd -P "$(dirname -- "${openwrt_vm_env_source}")" && pwd -P)"
OPENWRT_VM_REPO_ROOT="$(cd -P "${OPENWRT_VM_SCRIPT_DIR}/../.." && pwd -P)"
unset openwrt_vm_env_source

OPENWRT_VM_ENV_LOADED=1

OPENWRT_RELEASE="24.10.5"
OPENWRT_TARGET="armsr/armv8"
OPENWRT_IMAGE="openwrt-24.10.5-armsr-armv8-generic-ext4-combined-efi.img.gz"

OPENWRT_DOWNLOAD_BASE_URL="https://downloads.openwrt.org/releases/${OPENWRT_RELEASE}/targets/${OPENWRT_TARGET}"
OPENWRT_IMAGE_URL="${OPENWRT_DOWNLOAD_BASE_URL}/${OPENWRT_IMAGE}"
OPENWRT_SHA256_URL="${OPENWRT_DOWNLOAD_BASE_URL}/sha256sums"
OPENWRT_SHA256_ASC_URL="${OPENWRT_DOWNLOAD_BASE_URL}/sha256sums.asc"
OPENWRT_SHA256_SIG_URL="${OPENWRT_DOWNLOAD_BASE_URL}/sha256sums.sig"

QEMU_NET="user"
QEMU_HOST="127.0.0.1"
SSH_PORT="2222"
API_PORT="1444"
OPENWRT_VM_GUEST_IP="10.0.2.15"
OPENWRT_OVERLAY_STRATEGY="fresh-overlay-per-run"

OPENWRT_VM_WORK_DIR="${OPENWRT_VM_REPO_ROOT}/.tmp/openwrt-vm"
OPENWRT_VM_BASE_DIR="${OPENWRT_VM_WORK_DIR}/base"
OPENWRT_VM_RUN_DIR="${OPENWRT_VM_WORK_DIR}/run"
OPENWRT_VM_LOG_DIR="${OPENWRT_VM_WORK_DIR}/logs"
OPENWRT_VM_KEYS_DIR="${OPENWRT_VM_WORK_DIR}/keys"
OPENWRT_VM_STATE_DIR="${OPENWRT_VM_RUN_DIR}/state"

OPENWRT_IMAGE_ARCHIVE_PATH="${OPENWRT_VM_BASE_DIR}/${OPENWRT_IMAGE}"
OPENWRT_IMAGE_PATH="${OPENWRT_VM_BASE_DIR}/${OPENWRT_IMAGE%.gz}"
OPENWRT_SHA256_FILE="${OPENWRT_VM_BASE_DIR}/sha256sums"
OPENWRT_SHA256_ASC_FILE="${OPENWRT_VM_BASE_DIR}/sha256sums.asc"
OPENWRT_SHA256_SIG_FILE="${OPENWRT_VM_BASE_DIR}/sha256sums.sig"
OPENWRT_TEST_KEY_PATH="${OPENWRT_VM_KEYS_DIR}/id_ed25519"
OPENWRT_GPG_VERIFY_LOG="${OPENWRT_VM_BASE_DIR}/gpg-verify.log"
OPENWRT_FETCH_VERIFY_LOG="${OPENWRT_VM_BASE_DIR}/fetch-verify.log"
OPENWRT_VM_OVERLAY_DIR="${OPENWRT_VM_RUN_DIR}/overlays"
OPENWRT_VM_PID_FILE="${OPENWRT_VM_STATE_DIR}/qemu.pid"
OPENWRT_VM_OVERLAY_FILE="${OPENWRT_VM_STATE_DIR}/overlay.path"
OPENWRT_VM_SERIAL_LOG_FILE="${OPENWRT_VM_STATE_DIR}/serial-log.path"
OPENWRT_VM_MONITOR_SOCKET="${OPENWRT_VM_STATE_DIR}/qemu-monitor.sock"
OPENWRT_VM_SERIAL_SOCKET="${OPENWRT_VM_STATE_DIR}/qemu-serial.sock"
OPENWRT_VM_MONITOR_SOCKET_FILE="${OPENWRT_VM_STATE_DIR}/monitor-socket.path"
OPENWRT_VM_SERIAL_SOCKET_FILE="${OPENWRT_VM_STATE_DIR}/serial-socket.path"
OPENWRT_VM_BOOTSTRAP_STATE_FILE="${OPENWRT_VM_STATE_DIR}/serial-bootstrap.state"
OPENWRT_VM_READY_STATE_FILE="${OPENWRT_VM_STATE_DIR}/ready.state"

TP_API_BASE_URL="${TP_API_BASE_URL:-http://${QEMU_HOST}:${API_PORT}}"
TP_UI_BASE_URL="${TP_UI_BASE_URL:-http://127.0.0.1:3000}"
TP_REFRESH_ROUTE_FIXTURE="${TP_REFRESH_ROUTE_FIXTURE:-${OPENWRT_VM_SCRIPT_DIR}/fixtures/chnroute-valid.txt}"
TP_TEST_SUITE_TIER="${TP_TEST_SUITE_TIER:-blocking}"
TP_PLAYWRIGHT_ARTIFACT_DIR="${TP_PLAYWRIGHT_ARTIFACT_DIR:-${OPENWRT_VM_WORK_DIR}/playwright-artifacts}"

OPENWRT_GUEST_ROOT="/etc/transparent-proxy"
OPENWRT_GUEST_SERVER="/etc/transparent-proxy/server"
OPENWRT_GUEST_CONFIG="/etc/transparent-proxy/config.yaml"
OPENWRT_GUEST_ENABLE="/etc/transparent-proxy/enable.sh"
OPENWRT_GUEST_DISABLE="/etc/transparent-proxy/disable.sh"
OPENWRT_GUEST_INITD="/etc/init.d/transparent-proxy"
OPENWRT_GUEST_NFT_DIR="/etc/nftables.d"

export OPENWRT_VM_ENV_LOADED
export OPENWRT_VM_SCRIPT_DIR OPENWRT_VM_REPO_ROOT
export OPENWRT_RELEASE OPENWRT_TARGET OPENWRT_IMAGE
export OPENWRT_DOWNLOAD_BASE_URL OPENWRT_IMAGE_URL OPENWRT_SHA256_URL OPENWRT_SHA256_ASC_URL OPENWRT_SHA256_SIG_URL
export QEMU_NET QEMU_HOST SSH_PORT API_PORT OPENWRT_VM_GUEST_IP OPENWRT_OVERLAY_STRATEGY
export OPENWRT_VM_WORK_DIR OPENWRT_VM_BASE_DIR OPENWRT_VM_RUN_DIR OPENWRT_VM_LOG_DIR OPENWRT_VM_KEYS_DIR OPENWRT_VM_STATE_DIR
export OPENWRT_IMAGE_ARCHIVE_PATH OPENWRT_IMAGE_PATH OPENWRT_SHA256_FILE OPENWRT_SHA256_ASC_FILE OPENWRT_SHA256_SIG_FILE
export OPENWRT_GPG_VERIFY_LOG OPENWRT_FETCH_VERIFY_LOG OPENWRT_VM_OVERLAY_DIR OPENWRT_TEST_KEY_PATH
export OPENWRT_VM_PID_FILE OPENWRT_VM_OVERLAY_FILE OPENWRT_VM_SERIAL_LOG_FILE
export OPENWRT_VM_MONITOR_SOCKET OPENWRT_VM_SERIAL_SOCKET OPENWRT_VM_MONITOR_SOCKET_FILE OPENWRT_VM_SERIAL_SOCKET_FILE
export OPENWRT_VM_BOOTSTRAP_STATE_FILE OPENWRT_VM_READY_STATE_FILE
export TP_API_BASE_URL TP_UI_BASE_URL TP_REFRESH_ROUTE_FIXTURE TP_TEST_SUITE_TIER TP_PLAYWRIGHT_ARTIFACT_DIR
export OPENWRT_GUEST_ROOT OPENWRT_GUEST_SERVER OPENWRT_GUEST_CONFIG OPENWRT_GUEST_ENABLE OPENWRT_GUEST_DISABLE
export OPENWRT_GUEST_INITD OPENWRT_GUEST_NFT_DIR
