kind: pipeline
name: default
type: kubernetes

steps:
  - name: build-web
    image: node:lts-alpine
    commands:
      - cd portal
      - npm --registry=https://registry.npm.taobao.org install
      - npm run build
  - name: build
    image: golang:1.20
    environment:
      GOPROXY: https://registry.test4x.com/repository/go-proxy/
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64
    commands:
      - rm -rf guard/web
      - mv portal/build guard/web
      - cd guard
      - go build -o guard-bin
      - cp guard-bin ../
  - name: upx
    image: hairyhenderson/upx:3.96
    commands:
      - upx guard-bin
  - name: scp files
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: server
      username:
        from_secret: username
      key:
        from_secret: ssh_key
      port: 22
      source: guard-bin
      target: ~/
  - name: ssh deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: server
      username:
        from_secret: username
      key:
        from_secret: ssh_key
      port: 22
      script:
        - mv ~/guard-bin /etc/transparent-proxy/guard
        - /etc/init.d/transparent-proxy restart
  - name: notification
    when:
      status:
        - success
        - failure
    image: docker.test4x.com/xgfan/drone-bark:9dccad32
    settings:
      token:
        from_secret: bark_token
      title: "{DRONE_REPO} {DRONE_BUILD_STATUS}"
      content: "{DRONE_COMMIT_MESSAGE}"
