kind: pipeline
name: default
type: kubernetes

steps:
  - name: build-web
    image: node:lts-alpine
    commands:
      - cd proxy-portal
      - npm --registry=https://registry.npm.taobao.org install
      - RUN npm run build
  - name: build
    image: golang:1.18
    environment:
      GOPROXY: https://registry.test4x.com/repository/go-proxy/
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64
    commands:
      - mv proxy-portal/build watchdog/web
      - cd watchdog
      - go build -o watchdog-bin
      - cp watchdog-bin ../
  - name: upx
    image: hairyhenderson/upx:3.96
    commands:
      - upx watchdog-bin
  - name: scp files
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: server
      username:
        from_secret: username
      key:
        from_secret: ssh_key
      port: 22
      source: watchdog-bin
      target: ~/
  - name: ssh deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: server
      username:
        from_secret: username
      key:
        from_secret: ssh_key
      port: 22
      script:
        - mv ~/watchdog-bin /etc/transparent-proxy/watchdog
        - /etc/init.d/transparent-proxy-watchdog restart
  - name: notification
    when:
      status:
        - success
        - failure
    image: docker.test4x.com/xgfan/drone-bark:9dccad32
    settings:
      token:
        from_secret: bark_token
      title: "{DRONE_REPO} {DRONE_BUILD_STATUS}"
      content: "{DRONE_COMMIT_MESSAGE}"