#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
  procd_open_instance guard
  procd_set_param command /etc/transparent-proxy/guard -c /etc/transparent-proxy/config.yaml # service executable that has to run in **foreground**.
  # respawn automatically if something died, be careful if you have an alternative process supervisor
  # if process dies sooner than respawn_threshold, it is considered crashed and after 5 retries the service is stopped
  procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
  procd_set_param limits core="unlimited"                         # If you need to set ulimit for your process
  procd_set_param stdout 1                                        # forward stdout of the command to logd
  procd_set_param stderr 1                                        # same for stderr
  procd_set_param user root                                       # run service as user nobody
  procd_set_param pidfile /var/run/guard.pid # write a pid file on instance start and remove it on stop
  procd_close_instance
}
