export function normalizeIpForTestId(ip) {
  return String(ip || '').trim().replace(/[^0-9a-zA-Z]+/g, '-');
}

export const testIds = {
  navStatus: 'nav-status',
  navRules: 'nav-rules',
  navConfig: 'nav-config',
  navOps: 'nav-ops',
  statusPage: 'status-page',
  healthStatus: 'health-status',
  rulesCount: 'rules-count',
  totalRules: 'total-rules',
  setCard: (setName) => `set-card-${setName}`,
  rulesPage: 'rules-page',
  syncButton: 'sync-button',
  refreshButton: 'refresh-btn',
  setSelect: 'set-select',
  ipInput: 'ip-input',
  addBtn: 'add-btn',
  operationFeedback: 'operation-feedback',
  setCardRules: (setName) => `set-card-${setName}`,
  removeBtn: (setName, ip) => `remove-btn-${setName}-${normalizeIpForTestId(ip)}`,
  page: 'status-page',
  status: 'health-status',
  clientIp: 'client-ip',
  actionFeedback: 'operation-feedback',
  actionError: 'operation-feedback',
  setInput: (setName) => `ip-input`,
  setRemove: (setName, ip) => `remove-btn-${setName}-${normalizeIpForTestId(ip)}`,
};

export const selectors = {
  byTestId: (testId) => `[data-testid="${testId}"]`,
  navStatus: 'button:has-text("状态总览")',
  navRules: 'button:has-text("规则管理")',
  navConfig: 'button:has-text("配置管理")',
  navOps: 'button:has-text("运维中心")',
  statusPage: '.status-page',
  healthStatus: '.card-value.status-enabled, .card-value.status-disabled, .card-value.status-unknown',
  rulesCount: '.status-card:has(.card-label:has-text("规则集数量")) .card-value',
  totalRules: '.status-card:has(.card-label:has-text("规则总数")) .card-value',
  setCard: (setName) => `.set-card:has(.set-name:has-text("${setName}"))`,
  rulesPage: '.rules-page',
  syncButton: '.sync-btn',
  refreshButton: '.refresh-btn',
  setSelect: '.set-select',
  ipInput: '.ip-input',
  addBtn: '.add-btn',
  operationFeedback: '.operation-feedback',
  setCardRules: (setName) => `.rule-set:has(.rule-set-name:has-text("${setName}"))`,
  removeBtn: (setName, ip) => `.rule-set:has(.rule-set-name:has-text("${setName}")) .rule-item:has(.rule-ip:has-text("${ip}")) .remove-btn`,
  page: '.status-page',
  status: '.card-value.status-enabled, .card-value.status-disabled, .card-value.status-unknown',
  clientIp: '.card-value',
  actionFeedback: '.operation-feedback',
  actionError: '.operation-feedback.error',
  setInput: (setName) => '.ip-input',
  setRemove: (setName, ip) => `.rule-set:has(.rule-set-name:has-text("${setName}")) .rule-item:has(.rule-ip:has-text("${ip}")) .remove-btn`,
};
